wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1662041376.668313
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.10.4
      5: 0.13.2
      8:
      - 3
      - 8
      10:
      - 3
